spring:
  datasource:
    url: jdbc:h2:mem:profanator_db
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true