const Ingredient = require('../models/ingredient.cjs')

const INGREDIENTS = [
    new Ingredient({product: "Ambusher's Ring", name: 'Silver Ingot', quantity: 2}),
    new Ingredient({product: "Ambusher's Ring", name: 'Ixenite Ingot', quantity: 1}),
    new Ingredient({product: "Ambusher's Ring", name: 'Minor Purple Shard', quantity: 1}),
    new Ingredient({product: 'Anchor', name: 'Iron Ingot', quantity: 10}),
    new Ingredient({product: 'Antidote', name: 'Empty Vial', quantity: 1}),
    new Ingredient({product: 'Antidote', name: 'Floral Balm', quantity: 3}),
    new Ingredient({product: 'Antidote', name: 'Blood Berry', quantity: 3}),
    new Ingredient({product: 'Antidote Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Antidote Bomb', name: 'Volatile Essence', quantity: 1}),
    new Ingredient({product: 'Antidote Bomb', name: 'Blood Berry', quantity: 3}),
    new Ingredient({product: 'Antidote Bomb', name: 'Floral Balm', quantity: 4}),
    new Ingredient({product: 'Antidote Keg', name: 'Empty Keg', quantity: 1}),
    new Ingredient({product: 'Antidote Keg', name: 'Blood Berry', quantity: 60}),
    new Ingredient({product: 'Antidote Keg', name: 'Floral Balm', quantity: 60}),
    new Ingredient({product: 'Arcane Refiner Plan', name: 'Stone', quantity: 20}),
    new Ingredient({product: 'Arcane Refiner Plan', name: 'Wood', quantity: 10}),
    new Ingredient({product: 'Arcane Refiner Plan', name: 'Cobalt Ingot', quantity: 15}),
    new Ingredient({product: 'Arcane Refiner Plan', name: 'Molten Core', quantity: 4}),
    new Ingredient({product: 'Arcane Refiner Plan', name: 'Ghastly Flame', quantity: 5}),
    new Ingredient({product: 'Arcane Refiner Plan', name: 'Fermented Glowfruit', quantity: 5}),
    new Ingredient({product: 'Arcane Staff', name: 'Line Cloth', quantity: 2}),
    new Ingredient({product: 'Arcane Staff', name: 'Dark Wood', quantity: 4}),
    new Ingredient({product: 'Arcane Vestment Coat', name: 'Line Cloth', quantity: 35}),
    new Ingredient({product: 'Arcane Vestment Coat', name: 'Blue Mushroom', quantity: 5}),
    new Ingredient({product: 'Arcane Vestment Hood', name: 'Line Cloth', quantity: 40}),
    new Ingredient({product: 'Arcane Vestment Hood', name: 'Blue Mushroom', quantity: 7}),
    new Ingredient({product: 'Arcane Vestment Straps', name: 'Line Cloth', quantity: 60}),
    new Ingredient({product: 'Arcane Vestment Straps', name: 'Blue Mushroom', quantity: 15}),
    new Ingredient({product: 'Arrowhead', name: 'Iron Ingot', quantity: 1}),
    new Ingredient({product: 'Band of Concentration', name: 'Silver Ingot', quantity: 4}),
    new Ingredient({product: 'Band of Concentration', name: 'Minor Blue Shard', quantity: 1}),
    new Ingredient({product: 'Band of Longevity', name: 'Iron Ingot', quantity: 1}),
    new Ingredient({product: 'Band of Longevity', name: 'Silver Ingot', quantity: 3}),
    new Ingredient({product: 'Band of Longevity', name: 'Minor Red Shard', quantity: 1}),
    new Ingredient({product: 'Bardiche', name: 'Wood', quantity: 6}),
    new Ingredient({product: 'Bardiche', name: 'Leather', quantity: 1}),
    new Ingredient({product: 'Bardiche', name: 'Iron Ingot', quantity: 5}),
    new Ingredient({product: 'Barrel', name: 'Rope', quantity: 4}),
    new Ingredient({product: 'Barrel', name: 'Wood Plank', quantity: 12}),
    new Ingredient({product: 'Barrel', name: 'Iron Ingot', quantity: 4}),
    new Ingredient({product: 'Barrel', name: 'Iron Nails', quantity: 8}),
    new Ingredient({product: 'Battle Axe', name: 'Wood', quantity: 6}),
    new Ingredient({product: 'Battle Axe', name: 'Iron Ingot', quantity: 6}),
    new Ingredient({product: 'Battle Axe', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Battle Hammer', name: 'Wood', quantity: 8}),
    new Ingredient({product: 'Battle Hammer', name: 'Iron Ingot', quantity: 8}),
    new Ingredient({product: 'Battle Hammer', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Bleeding Arrow', name: 'Arrowhead', quantity: 1}),
    new Ingredient({product: 'Bleeding Arrow', name: 'Shaft', quantity: 1}),
    new Ingredient({product: 'Bleeding Arrow', name: 'Blood Berry', quantity: 2}),
    new Ingredient({product: 'Bleeding Arrow', name: 'Ghastly Flame', quantity: 2}),
    new Ingredient({product: 'Blunt Arrow', name: 'Arrowhead', quantity: 1}),
    new Ingredient({product: 'Blunt Arrow', name: 'Shaft', quantity: 1}),
    new Ingredient({product: 'Blunt Arrow', name: 'Iron Ingot', quantity: 1}),
    new Ingredient({product: 'Bodkin Arrow', name: 'Arrowhead', quantity: 3}),
    new Ingredient({product: 'Bodkin Arrow', name: 'Shaft', quantity: 3}),
    new Ingredient({product: 'Bone Armor Belt', name: 'Line Cloth', quantity: 4}),
    new Ingredient({product: 'Bone Armor Belt', name: 'Large Bones', quantity: 1}),
    new Ingredient({product: 'Bone Armor Boots', name: 'Line Cloth', quantity: 3}),
    new Ingredient({product: 'Bone Armor Boots', name: 'Bones', quantity: 3}),
    new Ingredient({product: 'Bone Armor Breast Plate', name: 'Line Cloth', quantity: 8}),
    new Ingredient({product: 'Bone Armor Breast Plate', name: 'Bones', quantity: 4}),
    new Ingredient({product: 'Bone Armor Breast Plate', name: 'Large Bones', quantity: 1}),
    new Ingredient({product: 'Bone Armor Gloves', name: 'Line Cloth', quantity: 2}),
    new Ingredient({product: 'Bone Armor Gloves', name: 'Bones', quantity: 2}),
    new Ingredient({product: 'Bone Armor Helmet', name: 'Line Cloth', quantity: 5}),
    new Ingredient({product: 'Bone Armor Helmet', name: 'Large Bones', quantity: 1}),
    new Ingredient({product: 'Bone Armor Shoulder Pad', name: 'Line Cloth', quantity: 5}),
    new Ingredient({product: 'Bone Armor Shoulder Pad', name: 'Large Bones', quantity: 1}),
    new Ingredient({product: 'Broadhead Arrow', name: 'Arrowhead', quantity: 3}),
    new Ingredient({product: 'Broadhead Arrow', name: 'Shaft', quantity: 3}),
    new Ingredient({product: 'Campfire', name: 'Wood', quantity: 5}),
    new Ingredient({product: 'Campfire', name: 'Flint', quantity: 1}),
    new Ingredient({product: 'Chest', name: 'Wood', quantity: 26}),
    new Ingredient({product: 'Chest', name: 'Rough Iron', quantity: 4}),
    new Ingredient({product: 'Cobalt Ingot', name: 'Rough Cobalt', quantity: 2}),
    new Ingredient({product: 'Cobalt Plate Boots', name: 'Cobalt Ingot', quantity: 4}),
    new Ingredient({product: 'Cobalt Plate Chest', name: 'Cobalt Ingot', quantity: 10}),
    new Ingredient({product: 'Cobalt Plate Gauntlets', name: 'Cobalt Ingot', quantity: 3}),
    new Ingredient({product: 'Cobalt Plate Gauntlets', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Cobalt Plate Helmet', name: 'Cobalt Ingot', quantity: 6}),
    new Ingredient({product: 'Cobalt Plate Pauldrons', name: 'Cobalt Ingot', quantity: 6}),
    new Ingredient({product: 'Cobalt Plate Waist', name: 'Cobalt Ingot', quantity: 5}),
    new Ingredient({product: 'Cobalt Plate Waist', name: 'Leather', quantity: 4}),
    new Ingredient({product: 'Empty Bursting Vial', name: 'Empty Vial', quantity: 1}),
    new Ingredient({product: 'Empty Bursting Vial', name: 'Crystal Blossom', quantity: 2}),
    new Ingredient({product: 'Empty Bursting Vial', name: 'Volatile Essence', quantity: 1}),
    new Ingredient({product: 'Empty Keg', name: 'Wood', quantity: 8}),
    new Ingredient({product: 'Empty Keg', name: 'Crystal Blossom', quantity: 2}),
    new Ingredient({product: 'Empty Keg', name: 'Rope', quantity: 2}),
    new Ingredient({product: 'Empty Keg', name: 'Wood Plank', quantity: 16}),
    new Ingredient({product: 'Empty Keg', name: 'Iron Ingot', quantity: 4}),
    new Ingredient({product: 'Empty Keg', name: 'Iron Nails', quantity: 8}),
    new Ingredient({product: 'Empty Vial', name: 'Crystal Blossom', quantity: 3}),
    new Ingredient({product: 'Explosion Keg', name: 'Empty Keg', quantity: 1}),
    new Ingredient({product: 'Explosion Keg', name: 'Fermented Glowfruit', quantity: 20}),
    new Ingredient({product: 'Explosion Keg', name: 'Molten Core', quantity: 40}),
    new Ingredient({product: 'Explosion Keg', name: 'Ghastly Flame', quantity: 40}),
    new Ingredient({product: 'Explosion Potion', name: 'Empty Vial', quantity: 1}),
    new Ingredient({product: 'Explosion Potion', name: 'Fermented Glowfruit', quantity: 1}),
    new Ingredient({product: 'Explosion Potion', name: 'Molten Core', quantity: 2}),
    new Ingredient({product: 'Explosion Potion', name: 'Ghastly Flame', quantity: 2}),
    new Ingredient({product: 'Explosion Potion Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Explosion Potion Bomb', name: 'Fermented Glowfruit', quantity: 1}),
    new Ingredient({product: 'Explosion Potion Bomb', name: 'Volatile Essence', quantity: 2}),
    new Ingredient({product: 'Explosion Potion Bomb', name: 'Molten Core', quantity: 4}),
    new Ingredient({product: 'Explosion Potion Bomb', name: 'Ghastly Flame', quantity: 1}),
    new Ingredient({product: 'Explosive Arrow', name: 'Arrowhead', quantity: 1}),
    new Ingredient({product: 'Explosive Arrow', name: 'Shaft', quantity: 1}),
    new Ingredient({product: 'Explosive Arrow', name: 'Fermented Glowfruit', quantity: 1}),
    new Ingredient({product: 'Explosive Arrow', name: 'Volatile Essence', quantity: 4}),
    new Ingredient({product: 'Explosive Arrow', name: 'Molten Core', quantity: 6}),
    new Ingredient({product: 'Explosive Arrow', name: 'Ghastly Flame', quantity: 2}),
    new Ingredient({product: 'Fertilizer Keg', name: 'Empty Keg', quantity: 1}),
    new Ingredient({product: 'Fertilizer Keg', name: 'Dung', quantity: 150}),
    new Ingredient({product: 'Fertilizer Keg', name: 'Molten Core', quantity: 60}),
    new Ingredient({product: 'Fertilizer Potion Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Fertilizer Potion Bomb', name: 'Dung', quantity: 5}),
    new Ingredient({product: 'Fertilizer Potion Bomb', name: 'Molten Core', quantity: 2}),
    new Ingredient({product: 'Flag', name: 'Wood', quantity: 25}),
    new Ingredient({product: 'Flag', name: 'Stone', quantity: 8}),
    new Ingredient({product: 'Flag', name: 'Rough Iron', quantity: 4}),
    new Ingredient({product: 'Flag', name: 'Leather', quantity: 5}),
    new Ingredient({product: 'Flame Keg', name: 'Empty Keg', quantity: 1}),
    new Ingredient({product: 'Flame Keg', name: 'Volatile Essence', quantity: 20}),
    new Ingredient({product: 'Flame Keg', name: 'Grog', quantity: 20}),
    new Ingredient({product: 'Flame Keg', name: 'Ghastly Flame', quantity: 20}),
    new Ingredient({product: 'Flame Potion', name: 'Empty Vial', quantity: 1}),
    new Ingredient({product: 'Flame Potion', name: 'Volatile Essence', quantity: 1}),
    new Ingredient({product: 'Flame Potion', name: 'Grog', quantity: 1}),
    new Ingredient({product: 'Flame Potion', name: 'Ghastly Flame', quantity: 1}),
    new Ingredient({product: 'Flame Potion Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Flame Potion Bomb', name: 'Volatile Essence', quantity: 5}),
    new Ingredient({product: 'Flame Potion Bomb', name: 'Grog', quantity: 2}),
    new Ingredient({product: 'Flame Potion Bomb', name: 'Ghastly Flame', quantity: 2}),
    new Ingredient({product: 'Flaming Arrow', name: 'Arrowhead', quantity: 1}),
    new Ingredient({product: 'Flaming Arrow', name: 'Shaft', quantity: 1}),
    new Ingredient({product: 'Flaming Arrow', name: 'Fermented Glowfruit', quantity: 2}),
    new Ingredient({product: 'Flaming Arrow', name: 'Volatile Essence', quantity: 2}),
    new Ingredient({product: 'Flint Arrow', name: 'Flint', quantity: 1}),
    new Ingredient({product: 'Flint Arrow', name: 'Stick', quantity: 1}),
    new Ingredient({product: 'Freezing Keg', name: 'Empty Keg', quantity: 1}),
    new Ingredient({product: 'Freezing Keg', name: 'Frost Needle', quantity: 160}),
    new Ingredient({product: 'Freezing Keg', name: 'Blue Mushroom', quantity: 20}),
    new Ingredient({product: 'Freezing Potion', name: 'Empty Vial', quantity: 1}),
    new Ingredient({product: 'Freezing Potion', name: 'Frost Needle', quantity: 8}),
    new Ingredient({product: 'Freezing Potion', name: 'Grog', quantity: 1}),
    new Ingredient({product: 'Freezing Potion Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Freezing Potion Bomb', name: 'Volatile Essence', quantity: 1}),
    new Ingredient({product: 'Freezing Potion Bomb', name: 'Frost Needle', quantity: 14}),
    new Ingredient({product: 'Freezing Potion Bomb', name: 'Grog', quantity: 2}),
    new Ingredient({product: 'Guild Hall', name: 'Stone', quantity: 1600}),
    new Ingredient({product: 'Guild Hall', name: 'Wood Plank', quantity: 1200}),
    new Ingredient({product: 'Guild Hall', name: 'Iron Ingot', quantity: 200}),
    new Ingredient({product: 'Guild Hall', name: 'Iron Nails', quantity: 200}),
    new Ingredient({product: 'Halberd', name: 'Wood', quantity: 6}),
    new Ingredient({product: 'Halberd', name: 'Leather', quantity: 1}),
    new Ingredient({product: 'Halberd', name: 'Iron Ingot', quantity: 4}),
    new Ingredient({product: 'Health Keg', name: 'Empty Keg', quantity: 1}),
    new Ingredient({product: 'Health Keg', name: 'Blood Berry', quantity: 120}),
    new Ingredient({product: 'Health Keg', name: 'Thorn Algae', quantity: 20}),
    new Ingredient({product: 'Health Potion', name: 'Empty Vial', quantity: 1}),
    new Ingredient({product: 'Health Potion', name: 'Blood Berry', quantity: 6}),
    new Ingredient({product: 'Health Potion', name: 'Thorn Algae', quantity: 1}),
    new Ingredient({product: 'Health Potion Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Health Potion Bomb', name: 'Volatile Essence', quantity: 1}),
    new Ingredient({product: 'Health Potion Bomb', name: 'Blood Berry', quantity: 8}),
    new Ingredient({product: 'Health Potion Bomb', name: 'Thorn Algae', quantity: 2}),
    new Ingredient({product: 'Heartseeker Ring', name: 'Iron Ingot', quantity: 5}),
    new Ingredient({product: 'Heartseeker Ring', name: 'Silver Ingot', quantity: 1}),
    new Ingredient({product: 'Heartseeker Ring', name: 'Minor Green Shard', quantity: 1}),
    new Ingredient({product: 'Improvised Bow', name: 'Stick', quantity: 10}),
    new Ingredient({product: 'Improvised Bow', name: 'Flint', quantity: 4}),
    new Ingredient({product: 'Improvised Bow', name: 'Leather', quantity: 1}),
    new Ingredient({product: 'Improvised Bow', name: 'Line Cloth', quantity: 1}),
    new Ingredient({product: 'Improvised Watchtower', name: 'Wood', quantity: 12}),
    new Ingredient({product: 'Improvised Watchtower', name: 'Rope', quantity: 8}),
    new Ingredient({product: 'Improvised Watchtower', name: 'Wood Plank', quantity: 30}),
    new Ingredient({product: 'Improvised Watchtower', name: 'Iron Ingot', quantity: 12}),
    new Ingredient({product: 'Improvised Watchtower', name: 'Iron Nails', quantity: 60}),
    new Ingredient({product: 'Iron Ingot', name: 'Rough Iron', quantity: 2}),
    new Ingredient({product: 'Iron Nails', name: 'Iron Ingot', quantity: 1}),
    new Ingredient({product: 'Iron Pickaxe', name: 'Wood', quantity: 6}),
    new Ingredient({product: 'Iron Pickaxe', name: 'Iron Ingot', quantity: 4}),
    new Ingredient({product: 'Iron Pickaxe', name: 'Leather', quantity: 1}),
    new Ingredient({product: 'Iron Plate Boots', name: 'Iron Ingot', quantity: 4}),
    new Ingredient({product: 'Iron Plate Chest', name: 'Iron Ingot', quantity: 10}),
    new Ingredient({product: 'Iron Plate Gauntlets', name: 'Iron Ingot', quantity: 3}),
    new Ingredient({product: 'Iron Plate Gauntlets', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Iron Plate Helmet', name: 'Iron Ingot', quantity: 6}),
    new Ingredient({product: 'Iron Plate Pauldrons', name: 'Iron Ingot', quantity: 6}),
    new Ingredient({product: 'Iron Plate Waist', name: 'Iron Ingot', quantity: 5}),
    new Ingredient({product: 'Iron Plate Waist', name: 'Leather', quantity: 4}),
    new Ingredient({product: 'Ixenite Ingot', name: 'Rough Ixenite', quantity: 2}),
    new Ingredient({product: 'Ixenite Plate Boots', name: 'Ixenite Ingot', quantity: 4}),
    new Ingredient({product: 'Ixenite Plate Chest', name: 'Ixenite Ingot', quantity: 10}),
    new Ingredient({product: 'Ixenite Plate Gauntlets', name: 'Ixenite Ingot', quantity: 3}),
    new Ingredient({product: 'Ixenite Plate Gauntlets', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Ixenite Plate Helmet', name: 'Ixenite Ingot', quantity: 6}),
    new Ingredient({product: 'Ixenite Plate Pauldrons', name: 'Ixenite Ingot', quantity: 6}),
    new Ingredient({product: 'Ixenite Plate Waist', name: 'Ixenite Ingot', quantity: 5}),
    new Ingredient({product: 'Ixenite Plate Waist', name: 'Leather', quantity: 4}),
    new Ingredient({product: 'Krekel Ingot', name: 'Rough Krekel', quantity: 2}),
    new Ingredient({product: 'Krekel Plate Boots', name: 'Krekel Ingot', quantity: 4}),
    new Ingredient({product: 'Krekel Plate Chest', name: 'Krekel Ingot', quantity: 10}),
    new Ingredient({product: 'Krekel Plate Gauntlets', name: 'Krekel Ingot', quantity: 3}),
    new Ingredient({product: 'Krekel Plate Gauntlets', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Krekel Plate Helmet', name: 'Krekel Ingot', quantity: 6}),
    new Ingredient({product: 'Krekel Plate Pauldrons', name: 'Krekel Ingot', quantity: 6}),
    new Ingredient({product: 'Krekel Plate Waist', name: 'Krekel Ingot', quantity: 5}),
    new Ingredient({product: 'Krekel Plate Waist', name: 'Leather', quantity: 4}),
    new Ingredient({product: 'Lamp Post', name: 'Wood', quantity: 8}),
    new Ingredient({product: 'Lamp Post', name: 'Stone', quantity: 20}),
    new Ingredient({product: 'Lamp Post', name: 'Flint', quantity: 2}),
    new Ingredient({product: 'Lamp Post', name: 'Iron Ingot', quantity: 2}),
    new Ingredient({product: 'Lamp Post', name: 'Volatile Essence', quantity: 3}),
    new Ingredient({product: 'Large Bag', name: 'Line Cloth', quantity: 26}),
    new Ingredient({product: 'Large Bag', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Large Bag', name: 'Thick Leather', quantity: 15}),
    new Ingredient({product: 'Large Bag', name: 'Rough Iron', quantity: 1}),
    new Ingredient({product: 'Large Farm Lot', name: 'Dung', quantity: 40}),
    new Ingredient({product: 'Large Farm Lot', name: 'Wood', quantity: 60}),
    new Ingredient({product: 'Large Farm Lot', name: 'Wood Plank', quantity: 80}),
    new Ingredient({product: 'Large Farm Lot', name: 'Iron Nails', quantity: 60}),
    new Ingredient({product: 'Large House', name: 'Wood', quantity: 200}),
    new Ingredient({product: 'Large House', name: 'Stone', quantity: 830}),
    new Ingredient({product: 'Large House', name: 'Wood Plank', quantity: 240}),
    new Ingredient({product: 'Large House', name: 'Iron Ingot', quantity: 18}),
    new Ingredient({product: 'Large House', name: 'Iron Nails', quantity: 50}),
    new Ingredient({product: 'Large Smelter', name: 'Wood', quantity: 60}),
    new Ingredient({product: 'Large Smelter', name: 'Rough Iron', quantity: 120}),
    new Ingredient({product: 'Leather Armor Belt', name: 'Leather', quantity: 4}),
    new Ingredient({product: 'Leather Armor Belt', name: 'Thick Leather', quantity: 2}),
    new Ingredient({product: 'Leather Armor Belt', name: 'Line Cloth', quantity: 3}),
    new Ingredient({product: 'Leather Armor Boots', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Leather Armor Boots', name: 'Thick Leather', quantity: 1}),
    new Ingredient({product: 'Leather Armor Boots', name: 'Line Cloth', quantity: 2}),
    new Ingredient({product: 'Leather Armor Cowl', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Leather Armor Cowl', name: 'Thick Leather', quantity: 1}),
    new Ingredient({product: 'Leather Armor Cowl', name: 'Line Cloth', quantity: 3}),
    new Ingredient({product: 'Leather Armor Gauntlets', name: 'Leather', quantity: 1}),
    new Ingredient({product: 'Leather Armor Gauntlets', name: 'Thick Leather', quantity: 1}),
    new Ingredient({product: 'Leather Armor Gauntlets', name: 'Line Cloth', quantity: 1}),
    new Ingredient({product: 'Leather Armor Guard', name: 'Leather', quantity: 5}),
    new Ingredient({product: 'Leather Armor Guard', name: 'Thick Leather', quantity: 4}),
    new Ingredient({product: 'Leather Armor Guard', name: 'Line Cloth', quantity: 4}),
    new Ingredient({product: 'Leather Armor Spaulders', name: 'Leather', quantity: 4}),
    new Ingredient({product: 'Leather Armor Spaulders', name: 'Thick Leather', quantity: 2}),
    new Ingredient({product: 'Leather Armor Spaulders', name: 'Line Cloth', quantity: 3}),
    new Ingredient({product: 'Line Cloth', name: 'Plant Fiber', quantity: 5}),
    new Ingredient({product: 'Mana Keg', name: 'Empty Keg', quantity: 1}),
    new Ingredient({product: 'Mana Keg', name: 'Blue Mushroom', quantity: 160}),
    new Ingredient({product: 'Mana Potion', name: 'Empty Vial', quantity: 1}),
    new Ingredient({product: 'Mana Potion', name: 'Blue Mushroom', quantity: 8}),
    new Ingredient({product: 'Mana Potion Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Mana Potion Bomb', name: 'Volatile Essence', quantity: 1}),
    new Ingredient({product: 'Mana Potion Bomb', name: 'Blue Mushroom', quantity: 10}),
    new Ingredient({product: "Marauder's Ring", name: 'Silver Ingot', quantity: 2}),
    new Ingredient({product: "Marauder's Ring", name: 'Cobalt Ingot', quantity: 1}),
    new Ingredient({product: "Marauder's Ring", name: 'Obsidian', quantity: 1}),
    new Ingredient({product: 'Medium Bag', name: 'Rough Iron', quantity: 1}),
    new Ingredient({product: 'Medium Bag', name: 'Line Cloth', quantity: 14}),
    new Ingredient({product: 'Medium Bag', name: 'Leather', quantity: 10}),
    new Ingredient({product: 'Medium Farm Lot', name: 'Dung', quantity: 18}),
    new Ingredient({product: 'Medium Farm Lot', name: 'Wood', quantity: 40}),
    new Ingredient({product: 'Medium Farm Lot', name: 'Wood Plank', quantity: 50}),
    new Ingredient({product: 'Medium Farm Lot', name: 'Iron Nails', quantity: 30}),
    new Ingredient({product: 'Medium House', name: 'Wood', quantity: 150}),
    new Ingredient({product: 'Medium House', name: 'Stone', quantity: 300}),
    new Ingredient({product: 'Medium House', name: 'Stick', quantity: 30}),
    new Ingredient({product: 'Medium House', name: 'Wood Plank', quantity: 45}),
    new Ingredient({product: 'Medium House', name: 'Iron Ingot', quantity: 22}),
    new Ingredient({product: 'Medium House', name: 'Iron Nails', quantity: 20}),
    new Ingredient({product: 'Phase Potion Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Phase Potion Bomb', name: 'Volatile Essence', quantity: 1}),
    new Ingredient({product: 'Phase Potion Bomb', name: 'Blue Mushroom', quantity: 3}),
    new Ingredient({product: 'Phase Potion Bomb', name: 'Comet Fruit', quantity: 3}),
    new Ingredient({product: 'Phase Potion Bomb', name: 'Frost Needle', quantity: 4}),
    new Ingredient({product: 'Phase Potion Bomb', name: 'Ghastly Flame', quantity: 3}),
    new Ingredient({product: 'Poison Keg', name: 'Empty Keg', quantity: 1}),
    new Ingredient({product: 'Poison Keg', name: 'Dung', quantity: 30}),
    new Ingredient({product: 'Poison Keg', name: 'Corrupted Root', quantity: 240}),
    new Ingredient({product: 'Poison Keg', name: 'Thorn Algae', quantity: 60}),
    new Ingredient({product: 'Poison Potion Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Poison Potion Bomb', name: 'Dung', quantity: 1}),
    new Ingredient({product: 'Poison Potion Bomb', name: 'Corrupted Root', quantity: 8}),
    new Ingredient({product: 'Poison Potion Bomb', name: 'Thorn Algae', quantity: 2}),
    new Ingredient({product: 'Poisonous Arrow', name: 'Arrowhead', quantity: 1}),
    new Ingredient({product: 'Poisonous Arrow', name: 'Shaft', quantity: 1}),
    new Ingredient({product: 'Poisonous Arrow', name: 'Molten Core', quantity: 1}),
    new Ingredient({product: 'Poisonous Arrow', name: 'Frost Needle', quantity: 1}),
    new Ingredient({product: 'Poisonous Arrow', name: 'Thorn Algae', quantity: 2}),
    new Ingredient({product: 'Potion of Gills', name: 'Empty Vial', quantity: 1}),
    new Ingredient({product: 'Potion of Gills', name: 'Comet Fruit', quantity: 2}),
    new Ingredient({product: 'Potion of Gills', name: 'Blood Berry', quantity: 3}),
    new Ingredient({product: 'Potion of Gills', name: 'Thorn Algae', quantity: 10}),
    new Ingredient({product: 'Primitive Axe', name: 'Stick', quantity: 8}),
    new Ingredient({product: 'Primitive Axe', name: 'Flint', quantity: 3}),
    new Ingredient({product: 'Primitive Hammer', name: 'Wood', quantity: 8}),
    new Ingredient({product: 'Primitive Hammer', name: 'Stone', quantity: 5}),
    new Ingredient({product: 'Primitive Hammer', name: 'Iron Ingot', quantity: 3}),
    new Ingredient({product: 'Primitive Pickaxe', name: 'Wood', quantity: 8}),
    new Ingredient({product: 'Primitive Pickaxe', name: 'Flint', quantity: 4}),
    new Ingredient({product: 'Range Target Dummy', name: 'Stick', quantity: 20}),
    new Ingredient({product: 'Range Target Dummy', name: 'Rope', quantity: 3}),
    new Ingredient({product: 'Range Target Dummy', name: 'Wood Plank', quantity: 3}),
    new Ingredient({product: 'Recurve Bow', name: 'Wood', quantity: 10}),
    new Ingredient({product: 'Recurve Bow', name: 'Flint', quantity: 8}),
    new Ingredient({product: 'Recurve Bow', name: 'Thick Leather', quantity: 2}),
    new Ingredient({product: 'Recurve Bow', name: 'Line Cloth', quantity: 1}),
    new Ingredient({product: 'Rope', name: 'Plant Fiber', quantity: 2}),
    new Ingredient({product: 'Sacred Shell Medallion', name: 'Cobalt Ingot', quantity: 3}),
    new Ingredient({product: 'Sacred Shell Medallion', name: 'Ambar', quantity: 1}),
    new Ingredient({product: 'Scarecrow', name: 'Wood', quantity: 6}),
    new Ingredient({product: 'Scarecrow', name: 'Line Cloth', quantity: 10}),
    new Ingredient({product: 'Scarecrow', name: 'Bones', quantity: 2}),
    new Ingredient({product: 'Scarecrow', name: 'Large Bones', quantity: 1}),
    new Ingredient({product: 'Scarecrow', name: 'Thick Leather', quantity: 5}),
    new Ingredient({product: 'Scarecrow', name: 'Rope', quantity: 4}),
    new Ingredient({product: 'Shaft', name: 'Stick', quantity: 1}),
    new Ingredient({product: 'Shelf', name: 'Wood Plank', quantity: 20}),
    new Ingredient({product: 'Shelf', name: 'Iron Nails', quantity: 10}),
    new Ingredient({product: 'Sigil of The Guardian', name: 'Silver Ingot', quantity: 4}),
    new Ingredient({product: 'Sigil of The Guardian', name: 'Minor Yellow Shard', quantity: 1}),
    new Ingredient({product: 'Silver Ingot', name: 'Rough Silver', quantity: 2}),
    new Ingredient({product: 'Silver Plate Boots', name: 'Silver Ingot', quantity: 4}),
    new Ingredient({product: 'Silver Plate Chest', name: 'Silver Ingot', quantity: 10}),
    new Ingredient({product: 'Silver Plate Gauntlets', name: 'Silver Ingot', quantity: 3}),
    new Ingredient({product: 'Silver Plate Gauntlets', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Silver Plate Helmet', name: 'Silver Ingot', quantity: 6}),
    new Ingredient({product: 'Silver Plate Pauldrons', name: 'Silver Ingot', quantity: 6}),
    new Ingredient({product: 'Silver Plate Waist', name: 'Silver Ingot', quantity: 5}),
    new Ingredient({product: 'Silver Plate Waist', name: 'Leather', quantity: 4}),
    new Ingredient({product: 'Small Bag', name: 'Line Cloth', quantity: 5}),
    new Ingredient({product: 'Small Bag', name: 'Leather', quantity: 2}),
    new Ingredient({product: 'Small Farm Lot', name: 'Dung', quantity: 6}),
    new Ingredient({product: 'Small Farm Lot', name: 'Wood', quantity: 20}),
    new Ingredient({product: 'Small Farm Lot', name: 'Wood Plank', quantity: 30}),
    new Ingredient({product: 'Small Farm Lot', name: 'Iron Nails', quantity: 10}),
    new Ingredient({product: 'Small Ship', name: 'Line Cloth', quantity: 80}),
    new Ingredient({product: 'Small Ship', name: 'Anchor', quantity: 1}),
    new Ingredient({product: 'Small Ship', name: 'Steering Wheel', quantity: 1}),
    new Ingredient({product: 'Small Ship', name: 'Rope', quantity: 30}),
    new Ingredient({product: 'Small Ship', name: 'Wood Plank', quantity: 170}),
    new Ingredient({product: 'Small Ship', name: 'Iron Nails', quantity: 60}),
    new Ingredient({product: 'Small Smelter', name: 'Wood', quantity: 20}),
    new Ingredient({product: 'Small Smelter', name: 'Rough Iron', quantity: 40}),
    new Ingredient({product: 'Small Table', name: 'Wood Plank', quantity: 12}),
    new Ingredient({product: 'Small Table', name: 'Iron Nails', quantity: 14}),
    new Ingredient({product: 'Spear', name: 'Wood', quantity: 6}),
    new Ingredient({product: 'Spear', name: 'Leather', quantity: 1}),
    new Ingredient({product: 'Spear', name: 'Iron Ingot', quantity: 4}),
    new Ingredient({product: 'Spiked Club', name: 'Wood', quantity: 5}),
    new Ingredient({product: 'Spiked Club', name: 'Line Cloth', quantity: 2}),
    new Ingredient({product: 'Spiked Club', name: 'Iron Nails', quantity: 12}),
    new Ingredient({product: 'Staff', name: 'Line Cloth', quantity: 1}),
    new Ingredient({product: 'Staff', name: 'Wood', quantity: 4}),
    new Ingredient({product: 'Standing Torch', name: 'Wood', quantity: 6}),
    new Ingredient({product: 'Standing Torch', name: 'Stick', quantity: 3}),
    new Ingredient({product: 'Standing Torch', name: 'Flint', quantity: 2}),
    new Ingredient({product: 'Standing Torch', name: 'Rope', quantity: 1}),
    new Ingredient({product: 'Steering Wheel', name: 'Wood', quantity: 8}),
    new Ingredient({product: 'Steering Wheel', name: 'Stone', quantity: 4}),
    new Ingredient({product: 'Steering Wheel', name: 'Rope', quantity: 1}),
    new Ingredient({product: 'Steering Wheel', name: 'Iron Ingot', quantity: 2}),
    new Ingredient({product: 'Steering Wheel', name: 'Iron Nails', quantity: 10}),
    new Ingredient({product: 'Straw House', name: 'Wood', quantity: 125}),
    new Ingredient({product: 'Straw House', name: 'Stone', quantity: 80}),
    new Ingredient({product: 'Straw House', name: 'Stick', quantity: 25}),
    new Ingredient({product: 'Straw House', name: 'Rough Iron', quantity: 15}),
    new Ingredient({product: 'Straw House', name: 'Rope', quantity: 8}),
    new Ingredient({product: 'Strong Grog Keg', name: 'Empty Keg', quantity: 1}),
    new Ingredient({product: 'Strong Grog Keg', name: 'Frost Needle', quantity: 20}),
    new Ingredient({product: 'Strong Grog Keg', name: 'Corrupted Root', quantity: 20}),
    new Ingredient({product: 'Strong Grog Keg', name: 'Floral Balm', quantity: 20}),
    new Ingredient({product: 'Strong Grog Keg', name: 'Grog', quantity: 20}),
    new Ingredient({product: 'Strong Grog Potion', name: 'Empty Vial', quantity: 1}),
    new Ingredient({product: 'Strong Grog Potion', name: 'Frost Needle', quantity: 1}),
    new Ingredient({product: 'Strong Grog Potion', name: 'Corrupted Root', quantity: 1}),
    new Ingredient({product: 'Strong Grog Potion', name: 'Floral Balm', quantity: 1}),
    new Ingredient({product: 'Strong Grog Potion', name: 'Grog', quantity: 1}),
    new Ingredient({product: 'Strong Grog Potion Bomb', name: 'Empty Bursting Vial', quantity: 1}),
    new Ingredient({product: 'Strong Grog Potion Bomb', name: 'Frost Needle', quantity: 2}),
    new Ingredient({product: 'Strong Grog Potion Bomb', name: 'Corrupted Root', quantity: 2}),
    new Ingredient({product: 'Strong Grog Potion Bomb', name: 'Floral Balm', quantity: 2}),
    new Ingredient({product: 'Strong Grog Potion Bomb', name: 'Grog', quantity: 2}),
    new Ingredient({product: 'Sword', name: 'Iron Ingot', quantity: 4}),
    new Ingredient({product: 'Sword', name: 'Leather', quantity: 1}),
    new Ingredient({product: 'Sword', name: 'Wood', quantity: 4}),
    new Ingredient({product: 'Training Dummy', name: 'Wood', quantity: 6}),
    new Ingredient({product: 'Training Dummy', name: 'Stick', quantity: 20}),
    new Ingredient({product: 'Training Dummy', name: 'Thick Leather', quantity: 8}),
    new Ingredient({product: 'Training Dummy', name: 'Rope', quantity: 6}),
    new Ingredient({product: 'Wood Plank', name: 'Wood', quantity: 4}),
    new Ingredient({product: 'Wooden Bench', name: 'Wood', quantity: 20}),
    new Ingredient({product: 'Wooden Bridge', name: 'Wood', quantity: 30}),
    new Ingredient({product: 'Wooden Bridge', name: 'Thick Leather', quantity: 6}),
    new Ingredient({product: 'Wooden Bridge', name: 'Rope', quantity: 8}),
    new Ingredient({product: 'Wooden Bridge', name: 'Wood Plank', quantity: 80}),
    new Ingredient({product: 'Wooden Bridge', name: 'Iron Nails',quantity: 80}),
    new Ingredient({product: 'Wooden Club', name: 'Wood', quantity: 5}),
    new Ingredient({product: 'Wooden Club', name: 'Line Cloth', quantity: 2}),
]

module.exports = INGREDIENTS