const Item = require("../models/item.cjs")

const ITEMS = [
    //ALCHEMY ITEMS
    new Item({proficiency: 'Alchemy', name: 'Antidote',  qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Antidote Keg', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Antidote Bomb', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Explosion Keg', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Explosion Potion', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Explosion Potion Bomb', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Fertilizer Keg', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Fertilizer Potion Bomb', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Flame Keg', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Flame Potion', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Flame Potion Bomb', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Freezing Keg', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Freezing Potion', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Freezing Potion Bomb', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Health Keg', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Health Potion', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Health Potion Bomb', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Mana Keg', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Mana Potion', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Mana Potion Bomb', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Phase Potion Bomb', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Poison Keg', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Potion of Gills', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Poison Potion Bomb', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Strong Grog Keg', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Strong Grog Potion', qtByProduction: 1}),
    new Item({proficiency: 'Alchemy', name: 'Strong Grog Potion Bomb', qtByProduction: 1}),
    
    //ARCHITECTURE ITEMS
    new Item({proficiency: 'Architecture', name: 'Flag', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Guild Hall', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Improvised Watchtower', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Large Farm Lot', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Large House', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Medium Farm Lot', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Medium House', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Small Farm Lot', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Small Ship', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Straw House', qtByProduction: 1}),
    new Item({proficiency: 'Architecture', name: 'Wooden Bridge', qtByProduction: 1}),
    
    //BLACKSMITH ITEMS
    new Item({proficiency: 'Blacksmith', name: 'Anchor', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Arrowhead', qtByProduction: 3}),
    new Item({proficiency: 'Blacksmith', name: 'Cobalt Plate Boots', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Cobalt Plate Chest', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Cobalt Plate Gauntlets', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Cobalt Plate Helmet', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Cobalt Plate Pauldrons', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Cobalt Plate Waist', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Bardiche', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Battle Axe', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Battle Hammer', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Halberd', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Iron Pickaxe', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Iron Plate Boots', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Iron Plate Chest', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Iron Plate Gauntlets', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Iron Plate Helmet', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Iron Plate Pauldrons', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Iron Plate Waist', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Ixenite Plate Boots', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Ixenite Plate Chest', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Ixenite Plate Gauntlets', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Ixenite Plate Helmet', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Ixenite Plate Pauldrons', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Ixenite Plate Waist', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Krekel Plate Boots', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Krekel Plate Chest', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Krekel Plate Gauntlets', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Krekel Plate Helmet', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Krekel Plate Pauldrons', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Krekel Plate Waist', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Large Smelter', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Primitive Axe', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Primitive Hammer', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Primitive Pickaxe', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Silver Plate Boots', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Silver Plate Chest', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Silver Plate Gauntlets', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Silver Plate Helmet', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Silver Plate Pauldrons', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Silver Plate Waist', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Spear', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Small Smelter', qtByProduction: 1}),
    new Item({proficiency: 'Blacksmith', name: 'Sword', qtByProduction: 1}),
    
    //BOWCRAFTING ITEMS
    new Item({proficiency: 'Bowcrafting', name: 'Bleeding Arrow', qtByProduction: 1}),
    new Item({proficiency: 'Bowcrafting', name: 'Blunt Arrow', qtByProduction: 1}),
    new Item({proficiency: 'Bowcrafting', name: 'Bodkin Arrow', qtByProduction: 3}),
    new Item({proficiency: 'Bowcrafting', name: 'Broadhead Arrow', qtByProduction: 3}),
    new Item({proficiency: 'Bowcrafting', name: 'Explosive Arrow', qtByProduction: 1}),
    new Item({proficiency: 'Bowcrafting', name: 'Flaming Arrow', qtByProduction: 1}),
    new Item({proficiency: 'Bowcrafting', name: 'Flint Arrow', qtByProduction: 3}),
    new Item({proficiency: 'Bowcrafting', name: 'Improvised Bow', qtByProduction: 1}),
    new Item({proficiency: 'Bowcrafting', name: 'Poisonous Arrow', qtByProduction: 1}),
    new Item({proficiency: 'Bowcrafting', name: 'Recurve Bow', qtByProduction: 1}),
    new Item({proficiency: 'Bowcrafting', name: 'Shaft', qtByProduction: 3}),
    
    //CARPENTRY ITEMS
    new Item({proficiency: 'Carpentry', name:'Arcane Staff', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Barrel', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Campfire', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Chest', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Empty Keg', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Lamp Post', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Range Target Dummy', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Scarecrow', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Shelf', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Small Table', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Spiked Club', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Staff', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Standing Torch', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Steering Wheel', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Training Dummy', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Wood Plank', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Wooden Bench', qtByProduction: 1}),
    new Item({proficiency: 'Carpentry', name:'Wooden Club', qtByProduction: 1}),
    
    //TAILORING ITEMS
    new Item({proficiency: 'Tailoring', name: 'Arcane Vestment Coat', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Arcane Vestment Hood', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Arcane Vestment Straps', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Bone Armor Belt', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Bone Armor Boots', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Bone Armor Breast Plate', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Bone Armor Gloves', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Bone Armor Helmet', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Bone Armor Shoulder Pad', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Large Bag', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Leather Armor Belt', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Leather Armor Boots', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Leather Armor Cowl', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Leather Armor Gauntlets', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Leather Armor Guard', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Leather Armor Spaulders', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Line Cloth', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Medium Bag', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Rope', qtByProduction: 1}),
    new Item({proficiency: 'Tailoring', name: 'Small Bag', qtByProduction: 1}),
    
    //TINKERING ITEMS
    new Item({proficiency: 'Tinkering', name: "Ambusher's Ring", qtByProduction: 1}),
    new Item({proficiency: 'Tinkering', name: 'Arcane Refiner Plan', qtByProduction: 1}),
    new Item({proficiency: 'Tinkering', name: 'Band of Concentration', qtByProduction: 1}),
    new Item({proficiency: 'Tinkering', name: 'Band of Longevity', qtByProduction: 1}),
    new Item({proficiency: 'Tinkering', name: 'Empty Bursting Vial', qtByProduction: 1}),
    new Item({proficiency: 'Tinkering', name: 'Empty Vial', qtByProduction: 1}),
    new Item({proficiency: 'Tinkering', name: 'Heartseeker Ring', qtByProduction: 1}),
    new Item({proficiency: 'Tinkering', name: 'Iron Nails', qtByProduction: 3}),
    new Item({proficiency: 'Tinkering', name: "Marauder's Ring", qtByProduction: 1}),
    new Item({proficiency: 'Tinkering', name: 'Sacred Shell Medallion', qtByProduction: 1}),
    new Item({proficiency: 'Tinkering', name: 'Sigil of The Guardian', qtByProduction: 1}),
    
    //RESOURCES ITEMS
    new Item({name: 'Ambar'}),
    new Item({name: 'Blood Berry'}),
    new Item({name: 'Blue Mushroom'}),
    new Item({name: 'Bones'}),
    new Item({name: 'Cobalt Ingot'}),
    new Item({name: 'Comet Fruit'}),
    new Item({name: 'Corrupted Root'}),
    new Item({name: 'Crystal Blossom'}),
    new Item({name: 'Dark Wood'}),
    new Item({name: 'Dung'}),
    new Item({name: 'Fermented Glowfruit'}),
    new Item({name: 'Flint'}),
    new Item({name: 'Floral Balm'}),
    new Item({name: 'Frost Needle'}),
    new Item({name: 'Ghastly Flame'}),
    new Item({name: 'Grog'}),
    new Item({name: 'Iron Ingot'}),
    new Item({name: 'Ixenite Ingot'}),
    new Item({name: 'Krekel Ingot'}),
    new Item({name: 'Large Bones'}),
    new Item({name: 'Leather'}),
    new Item({name: 'Minor Blue Shard'}),
    new Item({name: 'Minor Green Shard'}),
    new Item({name: 'Minor Purple Shard'}),
    new Item({name: 'Minor Red Shard'}),
    new Item({name: 'Minor Yellow Shard'}),
    new Item({name: 'Molten Core'}),
    new Item({name: 'Obsidian'}),
    new Item({name: 'Plant Fiber'}),
    new Item({name: 'Rough Cobalt'}),
    new Item({name: 'Rough Iron'}),
    new Item({name: 'Rough Ixenite'}),
    new Item({name: 'Rough Krekel'}),
    new Item({name: 'Rough Silver'}),
    new Item({name: 'Silver Ingot'}),
    new Item({name: 'Stick'}),
    new Item({name: 'Stone'}),
    new Item({name: 'Thick Leather'}),
    new Item({name: 'Thorn Algae'}),
    new Item({name: 'Volatile Essence'}),
    new Item({name: 'Wood'})
]

module.exports = ITEMS